# Generated by Django 6.0.2 on 2026-03-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': '3D модель', 'verbose_name_plural': '3D модели'},
        ),
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Превью'),
        ),
    ]
